### ISSUE TITLE
Conflict Twig syntax

### ISSUE THREAD

**Issue by Quberik** [zenwalker/node-beml#10]
Вот такое подключение файлов в шаблонизаторе Twig

    <script src="{{ asset("public/js/modernizr-2.6.2.min.js") }}"></script>

After BEML complete:

    <script src="{{ asset(" public="" js="" modernizr-2.6.2.min.js")="" }}"=""></script>

Twig syntax broken. 

Я так полагаю надо, что то поправить в файле ajson.js
Но не разобрался.. Суть в том, что Twig использует двойные фигурные скобки везде по своему коду {{ some }}.
Нужно написать правило, которое бы игнорировало содержимое между двойными фигурными скобками.

Может кто помочь?

**Comment by zenwalker** [comment]
Используй одинарные кавычки внутри двойных. Написанное даже с точки зрения HTML не валидно, не удивительно, что парсер с ума сходит: `src="{{ asset("` — парсер видит закрывающую кавычку, значит атрибут кончился.

**Comment by Quberik** [comment]
Да действительно, всё отлично стало. Спасибо, а то я уже разочаровался.
