### ISSUE TITLE
Plugin for Grunt

### ISSUE THREAD

**Issue by pepelsbey** [zenwalker/node-beml#4]
It would be good to be able specify a folder with generated HTML files that should be processed by beml, something similar or even identical to [grunt-contrib-htmlmin](https://www.npmjs.com/package/grunt-contrib-htmlmin)’s API.

```
grunt.initConfig({
  beml: {                        
    task: {                      
      options: {                 
        elemPrefix: '__',
        modPrefix: '_',
        modDlmtr: '_'
      },
      files: {                   
        'dist/index.html': 'src/index.html'
      }
    }
  }
});
```

**Comment by zenwalker** [comment]
Gulp plugin already written: https://github.com/zenwalker/gulp-beml.
I don't use grunt, but plugin for it is good idea. Thank. Will be created.

**Comment by zenwalker** [comment]
Completed: https://github.com/zenwalker/grunt-beml

**Comment by pepelsbey** [comment]
That was fast! Thank you so much :)
