### ISSUE TITLE
Support for binary modifiers

### ISSUE THREAD

**Issue by pepelsbey** [zenwalker/node-beml#5]
There’s a quite popular BEM notation promoted by Harry Roberts and Nicolas Gallagher:
```
block__element--modifier
```
Unlike classic BEM notation with `property_value` modifier, modification here is binary. So it would be good to be able to do something like this:
```
<div block="block" mod="size"></div>
<div class="block block--size"></div>
```
Currently it gives an error:
```
undefined:1
{"size"}
       ^
SyntaxError: Unexpected token }
```
Not sure if it would play nice with advanced JSON attributes, but it would make BEML much more flexible and popular. In my case it’s just a deal-breaker: I don’t use values in my modifiers.

**Comment by pepelsbey** [comment]
Actually I have found a hack: empty delimiter `modDlmtr: ''` and `mod="si:ze"` but it’s too ugly to use.

**Comment by zenwalker** [comment]
Now should work with syntax:

```html
<div block="block" mod="large"></div>
<div block="block" mod="large, color:red"></div>
```

```html
<div class="block block_large"></div>
<div class="block block_large block_color_red"></div>
```

**Comment by pepelsbey** [comment]
Thank you! Could you please also update Grunt/Gulp plugins?

**Comment by zenwalker** [comment]
Run `npm update grunt-beml`. Dependencies are automatically updated.
