### ISSUE TITLE
Mention limitations (or complex cases) in Readme

### ISSUE THREAD

**Issue by pepelsbey** [zenwalker/node-beml#6]
Yes, it’s me bothering you again :) It would be good to mention that due to BEML design limitation it’s not possible to get the following structure:
```
<div class="one">
	<div class="two__element"></div>
	<div class="two">
		<div class="one__element"></div>
	</div>
</div>
```
I wouldn’t call it a best practice but sometimes you don’t have a choice. And even if I’m wrong and it’s possible to achieve using `mix` or complex JSON-based values it still worth mentioning.

**Comment by zenwalker** [comment]
It is possible. You can use forced block notation:

```html
<div block="one">
  <div elem="element"></div>
  <div block="two">
    <div block="one" elem="element"></div>
  </div>
</div>
```

or mix (best practice in my view):

```html
<div block="one">
  <div elem="element"></div>
  <div elem="element-wrapper" mix="block:two">
    <div elem="element"></div>
  </div>
</div>
```

**Comment by pepelsbey** [comment]
It would be good to mention “forced block notation” then. Because it’s not obvious from the first look.

**Comment by zenwalker** [comment]
Okay. Thanks!
