### ISSUE TITLE
Empty elem & mod attributes

### ISSUE THREAD

**Issue by pepelsbey** [zenwalker/node-beml#7]
Currently if `elem` & `mod` attributes are empty they are treated like they still have an empty value and `elem` & `mod` are still applied in such cases.
```
<div block="block" elem="" mod=""></div>
<div class="block__ block__--"></div>
```
Wouldn’t it be smarter to just ignore them?
```
<div block="block" elem="" mod=""></div>
<div class="block"></div>
```
Use case is simple: sometimes it’s much easier to write `mod="{{ mod }}"` (and get no value if mod is just empty) than to remove/add attribute based on condition.

**Comment by zenwalker** [comment]
Should be fixed.
