### ISSUE TITLE
Maybe postHTML?

### ISSUE THREAD

**Issue by verybigman** [zenwalker/node-beml#8]
I think it would be possible to make a good plugin for [posthtml](https://github.com/posthtml/posthtml) ;)

**Comment by voischev** [comment]
:+1:

**Comment by zenwalker** [comment]
Maybe. What are the benefits?
Current implementation works without problems.

**Comment by verybigman** [comment]
This is true. But users will can chain beml with other plugins like plugins in postcss, man! It's pretty cool!)

**Comment by zenwalker** [comment]
It's cool. But chain of beml and postcss can be used in grunt/gulp.
Rewrite for rewriting is not my way. Thanks and sorry :)

**Comment by verybigman** [comment]
posthtml is not builder like a gulp or grunt. It's processor. You can chain plugins for work on html tree in json. This is absolutely another paradigm and instrument. You don't need rewrite all of your code. You can base plugin for posthtml on your library and create new repository. You really don't want do this?

**Comment by zenwalker** [comment]
@awinogradov sorry for long answer. BEML and PostHTML use different HTML parsers (bemjson and cheerio). This is not a problem? I don't need to rewrite code to another parser?

**Comment by voischev** [comment]
@zenwalker look at json tree after html
** html **
```html
<a block="b-animals" href="#">
    <span elem="cat" mod="size:big, color:red">Content</span>
</a>
```
** PostHTML tree **
```json
{
    tag: 'a',
    attrs: {
        block: 'b-animals',
        href: '#'
    },
    content: {
        tag: 'span',
        attrs: {
            elem: 'cat',
            mod: 'size:big, color:red'
        },
        content: 'Content'
    }
}
```

in plugin have to work only with this json tree. no parsers
